### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by silencht** [zihaomu/mediapipe_cmake#2]
```cmake
mediapipe_cmake/hair_segmenter/src/hair_segmenter.cpp:36:43: error: ‘readNetFromTflite’ is not a member of ‘cv::dnn’
   36 |     netSegmenter = makePtr<dnn::Net>(dnn::readNetFromTflite(buffer, buffer_size));
```

could you please give me some information to solve this error?
my cmake is successfully found opencv 4.7.0. so, I don't know why this error happend.

**Comment by zihaomu** [comment]
Hi @silencht. Thank you for trying this project. And sorry for this issues, because the project is still under development, it brings instability.

You can currently comment out `readNetFromTflite` to pass the compiling, I will try to release a stable version recently.

**Comment by zihaomu** [comment]
fixed
